aliases:
  - &testing_xcode
    os: osx
    language: objective-c
    script:
      - set -o pipefail
      - xcodebuild build-for-testing test-without-building -scheme VueFlux -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
      - xcodebuild build-for-testing test-without-building -scheme VueFlux -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' ENABLE_TESTABILITY=YES | xcpretty - c
      - xcodebuild build-for-testing test-without-building -scheme VueFlux -configuration Release -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV' ENABLE_TESTABILITY=YES | xcpretty -c
      - xcodebuild build -scheme VueFlux -configuration Release -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Series 4 - 40mm' ENABLE_TESTABILITY=YES | xcpretty -c

matrix:
  include:
    - <<: *testing_xcode
      osx_image: xcode10.1

    - <<: *testing_xcode
      osx_image: xcode10.2

notifications:
  email: false